 'use client';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Field, Msg, PageHead, Panel, useAction, useApi } from '@/components/admin/ui';

type Status = { values: Record<string, string>; configured: Record<string, boolean>; writable: boolean };
type Config = { title: string; help: string; fields: { key: string; label: string; choices?: [string, string][]; secret?: boolean }[]; test?: boolean };
const CONFIG: Record<string, Config> = {
  products: { title: 'Product API — 1688 / Taobao', help: '1688: search ও details; full variants, image search, pagination নেই। Taobao adapter পরীক্ষামূলক; details provider অনুযায়ী কাজ নাও করতে পারে।', test: true, fields: [{ key: 'provider', label: 'Provider', choices: [['mock', 'Mock / নমুনা'], ['alibaba-1688', 'RapidAPI — Alibaba 1688'], ['taobao-datahub', 'RapidAPI — Taobao DataHub (experimental)']] }, { key: 'apiKey', label: 'RapidAPI key', secret: true }, { key: 'cacheMinutes', label: 'Cache সময় (মিনিট: 1–10080)' }] },
  sms: { title: 'SMS / OTP', help: 'Alpha SMS সরাসরি কাজ করে। Generic HTTP provider-এর URL server environment-এ সেট করতে হবে। Console শুধু development-এর জন্য।', test: true, fields: [{ key: 'provider', label: 'Provider', choices: [['console', 'Console (development)'], ['alpha', 'Alpha SMS'], ['http', 'Generic HTTP (server URL)']] }, { key: 'apiKey', label: 'SMS API key', secret: true }, { key: 'senderId', label: 'অনুমোদিত Sender ID (optional)' }] },
  bkash: { title: 'bKash gateway', help: 'Credentials সংরক্ষণ করা মানে live payment যাচাই হয়েছে নয়। Sandbox-এ checkout পরীক্ষা করে Live করুন। Pending payment চলাকালে credentials বদলাবেন না।', fields: [{ key: 'environment', label: 'Environment', choices: [['sandbox', 'Sandbox'], ['live', 'Live']] }, { key: 'appKey', label: 'App key', secret: true }, { key: 'appSecret', label: 'App secret', secret: true }, { key: 'username', label: 'Username', secret: true }, { key: 'password', label: 'Password', secret: true }] },
  sslcommerz: { title: 'SSLCommerz — card / Nagad / bank', help: 'Payment method on/off আগের Website Content → Payment settings থেকে করুন। Credentials বদলানোর আগে pending payment শেষ করুন।', fields: [{ key: 'environment', label: 'Environment', choices: [['sandbox', 'Sandbox'], ['live', 'Live']] }, { key: 'storeId', label: 'Store ID', secret: true }, { key: 'storePassword', label: 'Store password', secret: true }] },
};
export default function Integrations() {
  const { data, err, loading, reload } = useApi<Record<string, Status>>('/admin/integrations');
  return <><PageHead title="API & Integrations" /><p className="mb-4 text-sm text-muted">শুধু Owner। খালি credential ঘর পুরোনো key রাখে; সরাতে নিচের checkbox ব্যবহার করুন। পরিবর্তন নতুন request-এ কার্যকর হবে।</p>{err && <p role="alert" className="text-danger">{err}</p>}{loading && !data && <p role="status">লোড হচ্ছে…</p>}{data && Object.entries(CONFIG).map(([kind, config]) => <IntegrationForm key={kind} kind={kind} config={config} status={data[kind]} reload={reload} />)}</>;
}
function IntegrationForm({ kind, config, status, reload }: { kind: string; config: Config; status: Status; reload: () => Promise<void> }) {
  const [values, setValues] = useState<Record<string, string>>({});
  const [clear, setClear] = useState<string[]>([]);
  const [testResult, setTestResult] = useState<{ ok: boolean; text: string } | null>(null);
  const act = useAction();
  useEffect(() => { setValues(status.values); setClear([]); }, [status]);
  const save = () => act.run(async () => { await api(`/admin/integrations/${kind}`, { method: 'PUT', json: { values, clearSecrets: clear } }); setTestResult(null); await reload(); }, 'সেটিংস সংরক্ষিত হয়েছে।');
  const test = () => act.run(async () => { const r = await api<{ ok: boolean; message: string }>(`/admin/integrations/${kind}/test`, { method: 'POST' }); setTestResult({ ok: r.ok, text: r.message }); }, 'সংযোগ পরীক্ষা শেষ।');
  return <Panel title={config.title} className="mb-4"><p className="text-sm text-muted">{config.help}</p>{!status.writable && <p role="alert" className="text-danger">Server-এ ৩২ অক্ষর বা বেশি INTEGRATIONS_ENCRYPTION_KEY সেট করুন।</p>}<form onSubmit={e => { e.preventDefault(); void save(); }} className="grid gap-3 md:grid-cols-2">{config.fields.map(field => <div key={field.key}><Field label={field.label}>{field.choices ? <select className="input" value={values[field.key] ?? ''} onChange={e => setValues(v => ({ ...v, [field.key]: e.target.value }))}>{field.choices.map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select> : <input className="input" type={field.secret ? 'password' : field.key === 'cacheMinutes' ? 'number' : 'text'} min={field.key === 'cacheMinutes' ? 1 : undefined} max={field.key === 'cacheMinutes' ? 10080 : undefined} autoComplete={field.secret ? 'new-password' : 'off'} value={values[field.key] ?? ''} placeholder={field.secret && status.configured[field.key] ? 'সেট করা আছে — বদলাতে নতুন value দিন' : ''} disabled={clear.includes(field.key)} onChange={e => setValues(v => ({ ...v, [field.key]: e.target.value }))} />}</Field>{field.secret && <label className="mt-1 flex items-center gap-2 text-sm"><input type="checkbox" checked={clear.includes(field.key)} onChange={e => setClear(v => e.target.checked ? [...v, field.key] : v.filter(k => k !== field.key))} />সংরক্ষিত credential সরান{status.configured[field.key] ? ' (সেট করা আছে)' : ' (সেট করা নেই)'}</label>}</div>)}<div className="flex flex-wrap gap-2 md:col-span-2"><button className="btn-gold" disabled={act.busy || !status.writable}>সংরক্ষণ করুন</button>{config.test && <button type="button" className="btn-outline" disabled={act.busy} onClick={() => void test()}>সংরক্ষিত সংযোগ পরীক্ষা</button>}</div></form>{config.test && <p className="text-xs text-muted">Product test একটি API search করতে পারে, provider quota খরচ হতে পারে। SMS test শুধু balance দেখে। আগে সেটিংস সংরক্ষণ করুন।</p>}<Msg m={act.msg} /><Msg m={testResult} /></Panel>;
}
